apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing-directory-apps
  labels:
    env: testing
spec:
  generators:
  - matrix:
      generators:
      - clusters: {}
      - list:
          elements:
          - appName: internal-app-rbac
            namespace: argocd
            manifestPath: manifests/testing
          - appName: fluentbit
            namespace: argocd
            manifestPath: manifests/testing/logging/fluentbit
          - appName: test-config
            namespace: argocd
            manifestPath: manifests/testing/configmap/config.yaml
  template:
    metadata:
      name: '{{name}}-{{appName}}'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=false
      source:
        repoURL: git@github.com:quyetmv/k8s-config.git
        targetRevision: HEAD
        path: '{{manifestPath}}'
        plugin:
          # [FIXED] Phải chỉ định chính xác tên plugin đã đăng ký trong Sidecar ConfigMap
          name: argocd-vault-plugin 
          env:
          - name: AVP_TYPE
            value: vault