apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-external-secrets'
      labels:
        app: external-secrets
        cluster: '{{name}}'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      sources:  # ← 2 SOURCES
      - repoURL: https://github.com/quyetmv/k8s-config.git  # Values repo
        targetRevision: main
        ref: values
      - repoURL: https://charts.external-secrets.io         # Chart repo ✅
        chart: external-secrets
        targetRevision: 0.10.4                               # Version đúng ✅
        helm:
          releaseName: external-secrets
          valueFiles:
          - $values/manifests/testing/externalsecret/values.yaml  # ✅ $values prefix
