apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing-helm-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters: {}
      - list:
          elements:
          - appName: ingress-internal
            chart: nginx-ingress
            repoURL: https://github.com/nginxinc/helm-charts
            targetRevision: 1.1.0
            valuesFile: manifests/testing/ingress/values-internal.yaml
            destNamespace: argocd

          - appName: ingress-external
            chart: nginx-ingress
            repoURL: https://github.com/nginx/ingress-nginx
            targetRevision: 4.11.2
            valuesFile: manifests/testing/ingress/values-external.yaml
            destNamespace: argocd

          - appName: external-secrets
            chart: external-secrets
            repoURL: https://charts.external-secrets.io
            targetRevision: 0.10.4
            valuesFile: manifests/testing/externalsecret/values.yaml
            destNamespace: argocd

          - appName: prometheus
            chart: kube-prometheus-stack
            repoURL: https://prometheus-community.github.io/helm-charts
            targetRevision: 65.5.0
            valuesFile: manifests/testing/prometheus/values.yaml
            destNamespace: argocd

  template:
    metadata:
      name: '{{.name}}-{{.appName}}'          
      labels:
        env: testing
        cluster: '{{.name}}'                  
        app: '{{.appName}}'                  

    spec:
      project: default
      destination:
        server: '{{.server}}'                
        namespace: '{{.destNamespace}}'      

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true

      ignoreDifferences:
      - group: apps
        kind: DaemonSet
        name: fluent-bit-*
      - group: apps
        kind: Deployment
        name: fluent-bit-*

      sources:
      - repoURL: git@github.com:quyetmv/k8s-config.git
        targetRevision: main
        ref: values

      - repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          releaseName: '{{.appName}}'        
          valueFiles:
          - $values/{{.valuesFile}}          
