apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing-helm-apps
  namespace: argocd
spec:
  goTemplate: true                                 # bật Go template (cần ArgoCD ≥ v2.8)
  generators:
  - matrix:
      generators:
      # Generator 1: lấy tất cả cluster có label env=testing (hoặc bất kỳ label nào bạn muốn)
      - clusters:
          selector:
            matchLabels:
              env: testing                       # bắt buộc mỗi cluster phải có label này và giá trị khác nhau hoặc giống nhau đều được

      # Generator 2: danh sách các Helm app
      - list:
          elements:
          - appName: ingress-internal
            chart: nginx-ingress
            repoURL: https://github.com/nginxinc/helm-charts
            version: 1.1.0
            valuesFile: k8s-config/manifests/testing/ingress/values-internal.yaml
            destNamespace: argocd

          - appName: ingress-external
            chart: nginx-ingress
            repoURL: https://github.com/nginx/ingress-nginx
            version: 4.11.2
            valuesFile: k8s-config/manifests/testing/ingress/values-external.yaml
            destNamespace: argocd

          - appName: external-secrets
            chart: external-secrets
            repoURL: https://charts.external-secrets.io
            version: 0.10.4
            valuesFile: k8s-config/manifests/testing/externalsecret/values.yaml
            destNamespace: external-secrets

          - appName: prometheus
            chart: kube-prometheus-stack
            repoURL: https://prometheus-community.github.io/helm-charts
            version: 65.5.0
            valuesFile: k8s-config/manifests/testing/prometheus/values.yaml
            destNamespace: monitoring

  template:
    metadata:
      name: '{{cluster}}-{{appName}}'                 # tên duy nhất trên toàn bộ ArgoCD
      labels:
        env: testing
        cluster: '{{cluster}}'
        app: '{{appName}}'

    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: '{{destNamespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true

      # Bỏ qua hoàn toàn lỗi Fluent Bit / Fluentd inject sidecar
      ignoreDifferences:
      - group: apps
        kind: DaemonSet
        name: fluent-bit-*
      - group: apps
        kind: Deployment
        name: fluent-bit-*

      sources:
      # Source 1: Helm chart từ registry
      - repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          releaseName: '{{appName}}'

      # Source 2: Chỉ lấy values.yaml từ repo config (không render YAML khác)
      - repoURL: https://github.com/quyetmv/k8s-config.git
        targetRevision: main
        path: .
        directory:
          recurse: false
          exclude: '{*.yaml,*.yml,*.json}'          # cực kỳ quan trọng
        helm:
          valueFiles:
          - '{{valuesFile}}'
