apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: avp-kustomize
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
