---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.110.84.78:8200"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLkNBRVNJRGlJNUliRFFWVDFjMXVUMkplWURHWHpIeUZPRmJwanByUWJ1SU1q
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-vault-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-vault-credentials
  dataFrom:
  - extract:
      key: quyetmv/testing/data/argocd-vault-credentials
