apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-argo-namespace
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: test-argo-namespace
subjects:
- kind: ServiceAccount
  name: test-argo-namespace-app
  namespace: test-argo-namespace
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
